// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8bhDeSrQ3GTdgZ70vTib7YCuFnOIU2YA',
    appId: '1:274671534628:web:184d8c43c51346e15a0eb1',
    messagingSenderId: '274671534628',
    projectId: 'siva-odoo',
    authDomain: 'siva-odoo.firebaseapp.com',
    storageBucket: 'siva-odoo.firebasestorage.app',
    measurementId: 'G-8B2QJV6LQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpkQ6wh0RKfidDZI2mScxgyJNxHK1cuO0',
    appId: '1:274671534628:android:12d2669c95f3d1355a0eb1',
    messagingSenderId: '274671534628',
    projectId: 'siva-odoo',
    storageBucket: 'siva-odoo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDECTEKY-D9Odc_6SKRl2oiDfh8OzpsMzE',
    appId: '1:274671534628:ios:9f4940394f59326f5a0eb1',
    messagingSenderId: '274671534628',
    projectId: 'siva-odoo',
    storageBucket: 'siva-odoo.firebasestorage.app',
    iosBundleId: 'com.example.odoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDECTEKY-D9Odc_6SKRl2oiDfh8OzpsMzE',
    appId: '1:274671534628:ios:9f4940394f59326f5a0eb1',
    messagingSenderId: '274671534628',
    projectId: 'siva-odoo',
    storageBucket: 'siva-odoo.firebasestorage.app',
    iosBundleId: 'com.example.odoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8bhDeSrQ3GTdgZ70vTib7YCuFnOIU2YA',
    appId: '1:274671534628:web:e4241923a32b36c55a0eb1',
    messagingSenderId: '274671534628',
    projectId: 'siva-odoo',
    authDomain: 'siva-odoo.firebaseapp.com',
    storageBucket: 'siva-odoo.firebasestorage.app',
    measurementId: 'G-1RQ5YEVNWG',
  );
}
